# Configuration for auto-assignment of issues and PRs

# Set to true to add reviewers to PRs
addReviewers: true

# Set to true to add assignees to PRs
addAssignees: true

# A list of reviewers to be added to PRs (GitHub user names)
reviewers:
  - dsm-project/maintainers

# A number of reviewers added to the PR
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1

# A list of assignees, overrides reviewers if set
# assignees:
#   - maintainer1
#   - maintainer2

# A number of assignees to add to the PRs
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 1

# A list of keywords to be skipped the process if PR's title include it
skipKeywords:
  - wip
  - draft
