image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cargo check --workspace
    command: |
      echo "Welcome to the DSM development environment!"
      echo "Run 'cargo build' to build the project"
      echo "Run 'cargo test' to run tests"
      
ports:
  - port: 7545
    onOpen: ignore
    visibility: public
  - port: 8765
    onOpen: ignore
    visibility: public
  - port: 9090
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - serayuzgur.crates
    - vadimcn.vscode-lldb
    - streetsidesoftware.code-spell-checker
    - yzhang.markdown-all-in-one
    - github.vscode-github-actions
