repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
        args: ['--all-targets']
    -   id: clippy

-   repo: https://github.com/DevinR528/cargo-sort
    rev: v1.0.9
    hooks:
    -   id: cargo-sort
        args: ['--workspace']
