# Workspace-level license policy configuration
# Schema compatible with cargo-deny v0.14.0+

[licenses]
# License allowlist - same as in dsm/deny.toml for consistency
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0", 
    "ISC",
    "Zlib",
    "MPL-2.0",
    "Unicode-3.0"
]
confidence-threshold = 0.8

# Version duplication configuration
[bans]
multiple-versions = "warn"
wildcards = "allow"

# Source registry validation
[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

# Security advisories checking
[advisories]
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
ignore = []
