# DSM License Policy Configuration
# Schema compatible with cargo-deny v0.14.0+

[licenses]
# Essential license allowlist for quantum-resistant cryptographic primitives
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0", 
    "ISC",
    "Zlib",
    "MPL-2.0",
    "Unicode-3.0"
]
confidence-threshold = 0.8

# Explicit license clarifications for ambiguous dependencies
[[licenses.clarify]]
name = "unicode-ident"
version = "*"
expression = "(MIT OR Apache-2.0) AND Unicode-3.0"
license-files = [
    { path = "LICENSE-UNICODE", hash = 0 },
    { path = "LICENSE-APACHE", hash = 0 },
    { path = "LICENSE-MIT", hash = 0 }
]

[[licenses.clarify]]
name = "arrayref"
version = "*"
expression = "BSD-2-Clause"
license-files = [{ path = "LICENSE", hash = 0 }]

[[licenses.clarify]]
name = "cloudabi"
version = "*"
expression = "BSD-2-Clause"
license-files = [{ path = "LICENSE", hash = 0 }]

[[licenses.clarify]]
name = "bip39"
version = "*"
expression = "CC0-1.0"
license-files = [{ path = "COPYING", hash = 0 }]

[[licenses.clarify]]
name = "bitcoin-internals"
version = "*"
expression = "CC0-1.0"
license-files = [{ path = "COPYING", hash = 0 }]

[[licenses.clarify]]
name = "bitcoin_hashes"
version = "*"
expression = "CC0-1.0"
license-files = [{ path = "COPYING", hash = 0 }]

[[licenses.clarify]]
name = "hex-conservative"
version = "*"
expression = "CC0-1.0"
license-files = [{ path = "COPYING", hash = 0 }]

[[licenses.clarify]]
name = "option-ext"
version = "*"
expression = "MPL-2.0"
license-files = [{ path = "LICENSE", hash = 0 }]

[[licenses.exceptions]]
name = "webpki"
version = "*"
allow = ["ISC"]

# Version duplication configuration
[bans]
multiple-versions = "warn"

# Quantum-resistant cryptographic dependency version exemptions
[[bans.skip]]
name = "getrandom"

[[bans.skip]]
name = "rand"

[[bans.skip]]
name = "rand_core"

[[bans.skip]]
name = "bitflags"

[[bans.skip]]
name = "regex-automata"

[[bans.skip]]
name = "regex-syntax"

[[bans.skip]]
name = "hashbrown"

[[bans.skip]]
name = "num-bigint"

[[bans.skip]]
name = "wasi"

[[bans.skip]]
name = "rustc-hash"

[[bans.skip]]
name = "zerocopy"

# Platform-specific dependency exemptions
[[bans.skip]]
name = "windows-sys"

[[bans.skip]]
name = "windows-targets"

[[bans.skip]]
name = "windows_aarch64_gnullvm"

[[bans.skip]]
name = "windows_aarch64_msvc"

[[bans.skip]]
name = "windows_i686_gnu"

[[bans.skip]]
name = "windows_i686_msvc"

[[bans.skip]]
name = "windows_x86_64_gnu"

[[bans.skip]]
name = "windows_x86_64_gnullvm"

[[bans.skip]]
name = "windows_x86_64_msvc"

[[bans.skip]]
name = "base64"

[[bans.skip]]
name = "bindgen"

# Source registry validation
[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
