[build]
# This flag enables conditional compilation for rust-analyzer
# It helps with macro expansion issues in the IDE
rustflags = ["--cfg", "rust_analyzer"]

[target.'cfg(all())']
rustflags = [
    # Enable all clippy lints except those explicitly allowed
    "-D", "warnings",
    # These are particularly important for cryptographic code
    "-D", "unsafe_code",
    # Performance optimizations that don't sacrifice safety
    "-C", "target-cpu=native",
]

# Toolchain configuration
[toolchain]
# The toolchain version should match what's in rust-toolchain.toml
channel = "nightly-2025-02-25"
components = ["rust-src", "rustfmt", "clippy"]
