name: PR Benchmarks

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled ]

jobs:
  benchmark:
    name: Performance Benchmarks
    if: contains(github.event.pull_request.labels.*.name, 'run-benchmarks')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # We need the full history for benchmark comparison
          
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install cargo-criterion
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-criterion
          
      - name: Run benchmarks
        run: cargo criterion --workspace
        
      - name: Publish benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Rust Benchmarks
          tool: 'criterion'
          output-file-path: target/criterion/results.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Alert if benchmark is 10% slower
          alert-threshold: '110%'
          comment-on-alert: true
          fail-on-alert: false
