name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: dsm
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # The logic below handles the npm publication:
      - name: Checkout Repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        
      - name: Setup Rust
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Build Release Package
        if: ${{ steps.release.outputs.release_created }}
        run: cargo build --release --workspace
        
      - name: Create Release Tarball
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mkdir -p release
          tar -czvf release/dsm-${{ steps.release.outputs.tag_name }}.tar.gz target/release/dsm target/release/dsm-storage-node
      
      - name: Upload Release Assets
        if: ${{ steps.release.outputs.release_created }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          files: release/dsm-${{ steps.release.outputs.tag_name }}.tar.gz
          generate_release_notes: true
