name: Scheduled Benchmarks

on:
  schedule:
    # Run weekly on Sunday at 2:00 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  benchmark:
    name: Run Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # We need the full history for benchmark comparison
          
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Run all benchmarks
        run: cargo bench --workspace
        
      - name: Collect and store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: DSM Core Benchmarks
          tool: 'cargo'
          output-file-path: target/criterion/results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Save and deploy GitHub Pages
          save-data-file: true
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: benchmarks
