name: Mark stale issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed in 14 days if no further activity occurs.'
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed in 14 days if no further activity occurs.'
          close-issue-message: 'This issue was closed due to inactivity.'
          close-pr-message: 'This PR was closed due to inactivity.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'bug,security,enhancement,documentation,help wanted'
          exempt-pr-labels: 'work-in-progress,security,waiting-for-review'
